name: Deploy to AWS
on:
    push:
        branches:
            - main
env:
    IMAGE_NAME: ${{ secrets.DOCKER_USERNAME }}/nextjs-todo-app:latest

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v3
            - name: build docker image
              run: docker build -t $IMAGE_NAME .
            - name: Login to DockerHub
              run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
            - name: Push to DockerHub
              run: docker push $IMAGE_NAME
    
    deploy:
        needs: build
        runs-on: self-hosted
        steps:
            - name: Pull Docker Image
              run: docker pull $IMAGE_NAME
            - name: Delete old container if exists
              run: docker rm -f nextjs-todo-app-container || true
            - name: Run Docker Container
              run: docker run -d -p 8698:8698 --name nextjs-todo-app-container $IMAGE_NAME


        

