name: Deploy to AWS
on:
    push:
        branches:
            - main

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v3
            - name: build docker image
              run: docker build -t nextjs-todo-app:latest .
            - name: Login to DockerHub
              run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
            - name: Push to DockerHub
              run: docker push nextjs-todo-app:latest
    
    deploy:
        needs: build
        runs-on: self-hosted
        steps:
            - name: Pull Docker Image
              run: docker pull nextjs-todo-app:latest
            - name: Delete old container if exists
              run: docker rm -f nextjs-todo-app-container || true
            - name: Run Docker Container
              run: docker run -d -p 8698:8698 --name nextjs-todo-app-container nextjs-todo-app:latest


        

